In [1]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("winedata - sheet1.csv")

In [36]:
df

,Year,WHO region,Country,Beverage Types,Display Value
0,1986,Western Pacific,Viet Nam,Wine,0.00
1,1986,Americas,Uruguay,Other,0.50
2,1985,Africa,Cte d'Ivoire,Wine,1.62
3,1986,Americas,Colombia,Beer,4.27
4,1987,Americas,Saint Kitts and Nevis,Beer,1.98
...,...,...,...,...,...
95,1984,Africa,Niger,Other,0.00
96,1985,Europe,Luxembourg,Wine,7.38
97,1984,South-East Asia,Indonesia,Wine,0.00
98,1984,Africa,Equatorial Guinea,Wine,0.00
99,1985,South-East Asia,Democratic People's Republic of Korea,Wine,0.00

Q1) 
Write a Pandas program to display the dimensions or shape of the World alcohol 
consumption dataset. Also extract the column names from the dataset

In [37]:
df.shape

(100, 5)

In [38]:
df.columns

Index(['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'], dtype='object')

In [39]:
# Q2) Write a Pandas program to find out the alcohol consumption details in the year '1987' or '1989' from the world alcohol consumption dataset  
df.query("Year == 1987 | Year == 1989").head()
df.loc[(df["Year"] == 1987) | (df["Year"] == 1989)].head()

    Year WHO region                Country Beverage Types  Display Value
4   1987   Americas  Saint Kitts and Nevis           Beer           1.98
5   1987   Americas              Guatemala          Other           0.00
6   1987     Africa              Mauritius           Wine           0.13
10  1987     Africa               Botswana           Wine           0.20
11  1989   Americas              Guatemala           Beer           0.62

In [47]:
# Q3) Write a Pandas program to find out the alcohol consumption details by the 'Americas' in the year '1985' from the world alcohol consumption dataset  
# df.loc[(df["Year"] == 1985) & (df["WHO region"] == 'Americas')]
df.query("Year == 1985 and `WHO region` == 'Americas'")

    Year WHO region                Country Beverage Types  Display Value
35  1985   Americas  Saint Kitts and Nevis        Spirits           2.24

In [55]:
# Q4) Write a Pandas program to find out the alcohol consumption details in the year '1986' where WHO region is 'Western Pacific' and country is 'VietNam' from the world alcohol consumption dataset.
# df.loc[
#     (df["Year"] == 1986)
#     & (df["WHO region"] == "Western Pacific")
#     & (df["Country"] == "Viet Nam")
# ]
df.query("Year == 1985 and `WHO region` == 'Western Pacific' and Country == 'Viet Nam'")

    Year       WHO region   Country Beverage Types  Display Value
14  1985  Western Pacific  Viet Nam        Spirits           0.05

In [57]:
# Q5) Write a Pandas program to find out the alcohol consumption details in the year '1986' or '1989' where WHO region is 'Americas' or 'Europe' from the world alcohol consumption dataset.
df.query("Year == 1986 or Year == 1989 and `WHO region` == 'Americas' or `WHO region` == 'Europe'").head()
# df.loc[
#     (df["Year"] == 1986)
#     | (df["Year"] == 1989) & (df["WHO region"] == "Americas")
#     | (df["WHO region"] == "Europe")
# ].head()

    Year       WHO region              Country Beverage Types  Display Value
0   1986  Western Pacific             Viet Nam           Wine           0.00
1   1986         Americas              Uruguay          Other           0.50
3   1986         Americas             Colombia           Beer           4.27
8   1986         Americas  Antigua and Barbuda        Spirits           1.55
11  1989         Americas            Guatemala           Beer           0.62